server:
  port: ${port:8005}
spring:
  application:
    name: consumer
  cloud:
    nacos:
      discovery:
#        server-addr: localhost:8848,localhost:8845,localhost:8851
        server-addr: localhost:8848
        namespace: 637dd07e-91d4-4fc7-867d-45be3719f3cb
        group: MICROCLOUD_GROUP # 一般建议大写
        cluster-name: YootkCluster # 配置集群名称
provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#ribbon:
#  ConnectTimeout: 5000          # 创建连接的超时时间，单位：ms
#  ReadTimeout: 5000             # 在连接创建好以后，调用接口的超时时间，单位：ms
#  MaxAutoRetries: 1             # 最大重试次数
#  MaxAutoRetriesNextServer: 2   # 切换到下个微服务实例的重试次数
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
